### ISSUE TITLE
Accidental clashing with admin username and imported user

### ISSUE THREAD

**Issue by psychobunny** [akhoury/nodebb-plugin-import#109]
![](http://i.imgur.com/aCM12v5.png)

If I were to deselect this, and decided to import a huge DB, there's no guarantee that I might not accidentally clobber somebody else's posts and render them as a guest. Unless I'm reading this wrong?

**Comment by psychobunny** [comment]
If you think the admin should do a check on MySQL etc first for an existing username then that's fair enough to close, just thought I'd bring it up

**Comment by akhoury** [comment]
well, yea, the thing is each adaptor would need to provide an interface to check for the existing. Since each MySQL schema is different. I am not saying it's not doable, I think it's OK to leave some of this initial leg work for the main Admin to decide on pre-import.

Another thing I could do is check EACH username on creation, if it clashes with the admin uid=1, then make the switch, and transfer each post/topic to the uid=1 - in another words, behave like this checkbox is ALWAYS checked, but let the import process detect what is the username in question.

leave it open, I think I can make it simpler

**Comment by akhoury** [comment]
closing this one in favor of its superset https://github.com/akhoury/nodebb-plugin-import/issues/144
