### ISSUE TITLE
Is there a way to replace sortedSetCard with a counter?

### ISSUE THREAD

**Issue by barisusakli** [akhoury/nodebb-plugin-import#118]
https://github.com/akhoury/nodebb-plugin-import/blob/master/server/data.js#L36

Can get really slow when there are hunders of thousands of elements.

**Comment by barisusakli** [comment]
If this is only called once per import then just ignore this. But if its called repeatedly then It will get slower as more and more users are imported.

**Comment by akhoury** [comment]
this gets called post import. 

Say you want to convert all the content to Markdown after the import was done, then I just called it once per "operation" (I count all posts, all topics, all users, all categories once). I don't think that's too expensive though

plus, I am counting records in the database, there is no easy way for me to keep count, I can't hold this in memory because, the server might go-down/be-killed/crash and I still want to be able to count the records.

To be honest, i only use this to provide percentage-feedback to the user, if the user is willing to wait with no progress feedback (10%, 20%.... ) then I really don't need to count the records.

**Comment by barisusakli** [comment]
Yeah I looked through the code and I don't see it being called too frequently so It should be fine.
