### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by NiftyXXL** [akhoury/nodebb-plugin-import#93]
Vbulletin & mybb support attachments (on Postings)- it would be nice if we could import them.

**Comment by bdharrington7** [comment]
Hey @akhoury, while you're working on getting it to work for 0.8.x, are you doing that refactor you were talking about before your break? I've been holding off any PR's for more functionality I was hoping to add.

**Comment by akhoury** [comment]
hmm - nodebb support attachments on posts?

**Comment by akhoury** [comment]
and I reverted a lot of my refactor-changes, I changed my mind on few things, I think I'm gonna use promises to avoid the horrible callback nesting I am doing now.
btw, 0.8.2 is supported on master now, i just have to do more testing before I release.

If you have a "small" PR, I can merge in,

**Comment by bdharrington7** [comment]
That's the problem, judging by my last pr, I didn't think adding a new type of import was going to be "small" at all, so I was waiting for a refactor. Using Promises sounds like a good pattern, dealing with all those callbacks was... fun :) 

The attachments functionality was pretty simple, it's just a MD link that points to the uploaded file. I'm not sure it can get / we want it to get more complicated than that.

**Comment by akhoury** [comment]
> it's just a MD link 

I think it should be an HTML anchor - this way it's compatible with BBCode and MD - then the import-user have the option to convert either to MD via the post-import tools.

> that points to the uploaded file

Does that mean the files would need to stay where they are - what if we copy then down to nodebb's public dir, i..e. `/public/attachments/_pid_attachment_index.extension`
I don't know.. just thinking out loud.

As for the refactor, I am crazy busy, like buried with backlog work, I need to be trapped alone somewhere with a laptop for 186.32 years to be done - maybe I will do it once NodeBB 1.0 is out, you know for the celebration.

**Comment by bdharrington7** [comment]
> I think it should be an HTML anchor

 Good call, I agree

> Does that mean the files would need to stay where they are - what if we copy then down to nodebb's public dir

Possible, Was just thinking of ways to minimize IO if we can just include in the instructions to put the folder in the right spot

**Comment by akhoury** [comment]
I say, just transfer them as anchors - it might require some HTTP server re-routing knowledge to get them to work right, and it someone insists on moving them into the nodebb/public folder they can, then with some regex, they re-iterate over the whole db, search and replace.

### option-1

Use the `parseBefore()` (or `parseAfter()`) advanced-option in the Post-Import Tools, where you write your own javascript to edit the content of each post content, then select the __"Dont touch my content"__, that will iterate over all posts (or whatever records you choose and execute your javascript)

Old-screenshot but same idea: 
https://cloud.githubusercontent.com/assets/1398375/4211624/ac24a21e-388c-11e4-989e-230855a3f116.png

## Option-2

Write your own script to edit the data, something like this.

```javascript
       // assuming you're in NodeBB/node_modules/nodebb-plugin-import/server

        var Data = require("./data.js");
        var Posts = require('../../../src/posts.js');
        
        Data.eachPost(
            function(post, next) {
                 var newContent = post.content.replace(/apples/, 'oranges'); // or you can use the original post. _imported_content if you haven't deleted them.

                 Posts.setPostField(post.pid, 'content', newContent, next);
            }, 
            {async: true, eachLimit: 10}, 
            function(err) {
                if (err) throw err;
                console.log("ALL DONE");
            }
        );
```

**Comment by bdharrington7** [comment]
My thought was going with Option 2, since there's data (at least stored in Vanilla databases) that records information about each upload such as who uploaded it, which post it was attached to, etc.

**Comment by thomasfrivold** [comment]
Does the vanilla-data-exporter support ATTACHMENTS?

It's a really big deal. 

Also private messages. Conversations, not so much..

**Comment by bdharrington7** [comment]
@thomasfrivold it's in progress. The importer needs to support it first, then the vanilla exporter can support it

**Comment by bdharrington7** [comment]
For attachments that is. On vanilla aren't conversations the same thing as private messages? Is that a different plugin?

**Comment by thomasfrivold** [comment]
Vanilla has a very very cool feature where you can add as many recipients you like and start a message stream to all users. So if I talk to Jessica about the party on Saturday, I can add Jenny the "conversation" and ask here if she'll bring her special nuclear bikini.... See what I mean?

**Comment by bdharrington7** [comment]
Yeah, I use vanilla forums but it's not a very used feature in my community. 

Currently nodebb doesn't even support multi-person chats so it wouldn't import correctly anyway.

-Brian

**Comment by akhoury** [comment]
@bdharrington7, __re: attachments__ i'm thinking that each `_topic` and `_post` record, would have an array of `_attachments` on it, kinda like `topic._tags` today, ([screenshot](https://cloud.githubusercontent.com/assets/1398375/11226726/b2439b82-8d4f-11e5-96ec-633c9a7a9432.png)) ([docs](https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md#yourmodulegetpaginatedtopicsstart-limit-callback))

### `post` example (same for topic)
```
"{
  "_pid": 65487,
  "_tid": 1234,
  "_uid": 202,

  "_attachments": ["http://example.com/abc/xyz.zip", "http://example.com/abc/xyz2.zip"], // <--- basically an array of URLs

  "_guest": "Some dude",
  "_ip": "123.456.789.012",
  "_content": "Post content ba dum tss",
  "_reputation": 0,
  "_votes": 0,
  "_timestamp": 1386475829970,
  "_path": "/myoldforum/topic/123#post56789",
  "_slug": "old-post-slug"
}"
```

This way, it's the expoter's job to make the necessary `JOIN` an include those 
Now since NodeBB doesn't really support attachments, I am think the importer would do 2 things:

* 1st) it will save on each `post/topic` record an `_imported_attachements` field, just like it does for all other fields - that would be useful, if sometime in the future, one decides to use a different plugin for attachments representation, or monitoring or whatever
* 2nd) it will expose an option in the Post-Import-Tools > Convert to optionally allow the use to "merge attachments in content, while converting to Markdown" (something in that sense) - which will essentially iterate over each record's attachments, and a link to it at the bottom of the content.

Now if the attachments are saved as blobs in the source database, we can also support that, by something like `_attachmentsBlobs` array - and the importer will essentially write those blobs to the public directory of nodebb, then populate the `_attachments` array with relative urls to that directory, with unique filenames, the only thing is that we don't know what each file type is, so the attachmentsBlobs items are NOT strings, they need to include the binary and either a filename or extension. 

```
_attachmentsBlobs: [
      {
           blob: <BINARY-BLOB>  // required
          
           // one these is required, the filename will be prefixed with a unique value anyways
           filename: "abc.zip" 
           extension: ".zip" // if no filename is passed, one would be generated.
       }
]
```

let me know what you think?

@thomasfrivold as @bdharrington7 mentioned, NodeBB does not support "multi-chat" conversations, so we cannot really import them - if you still want to migrate to NodeBB, I suggest you:

* definitely keep a copy of your Vanilla database dump 
* file a feature request with the NodeBB team to support multi-chat, 

Once multi-chat is supported, I can probably add this feature here, and allow you to import JUST these conversations from your Vanilla DB - as long, of course, you didn't click that big red button in the Importer > Post-Import Tools 

![screen shot 2015-11-17 at 5 42 17 pm](https://cloud.githubusercontent.com/assets/1398375/11227210/ae6858ec-8d52-11e5-93ec-e8ea9a539a42.png)

**Comment by bdharrington7** [comment]
I think this would be a pretty good approach, I was just wondering if we should always run uploads through the nbb uploads module to fire the right hooks, hence my original post. I'm not sure about the performance implications of doing that would be though

**Comment by akhoury** [comment]
On the latest nodebb-plugin-import@0.3.24 you can now either attach urls or blobs, or both at the same time, supported on [_topics](https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md#yourmodulegetpaginatedtopicsstart-limit-callback-required-function) and on [_posts](https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md#yourmodulegetpaginatedpostsstart-limit-callback-required-function)

```javascript
... 
        "_attachments": ["http://example.com/myfile.zip"], // OPTIONAL, an array of urls, to append to the content for download.

        // OPTIONAL, an array of objects, each object mush have the binary BLOB,
        // either a filename or extension, then each file will be written to disk,
        // if no filename is provided, the extension will be used and a filename will be generated as attachment_t_{_tid}_{index}{extension}
        // and its url would be appended to the _content for download
        "_attachmentsBlobs": [ {blob: <BINARY>, filename: "myfile.zip"}, {blob: <BINARY>, extension: ".zip"} ],
...
```

Obviously writing blobs to disk is going to slow down the importing process, so, if the files are already on disk, put them in nodebb's public folder or somewhere accessible and have your plugin just populates the `_attachments` array and not the `_attachmentsBlobs` array

**Comment by akhoury** [comment]
<img width="1516" alt="screen shot 2015-12-18 at 11 56 03 pm" src="https://cloud.githubusercontent.com/assets/1398375/11911429/01d21376-a5e3-11e5-931a-85761312486a.png">
